[project]
name = "mcp-qbittorrent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "fastmcp>=2.12.4",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.11.0",
]
